TOPDIR = ..

include $(TOPDIR)/defs.mk

YANG = $(wildcard *.yang)

PYANGFLAGS = 

INSTALLYANG = $(YANG)

CATEGORY_ietf-inet-types.yang = common
CATEGORY_ietf-yang-types.yang = common
CATEGORY_ietf-yang-types@2010-09-24.yang = common
CATEGORY_ietf-netconf-monitoring.yang = common

CATEGORY_iana-entity.yang = equipment
CATEGORY_ietf-entity.yang = equipment

CATEGORY_iana-if-type.yang = interface
CATEGORY_ietf-interfaces.yang = interface

include $(TOPDIR)/rules.mk
